# Generated by Django 4.0.6 on 2022-07-28 16:58

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('gimmo', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contrat',
            name='prochainpay',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
