# Generated by Django 4.0.6 on 2022-07-29 23:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gimmo', '0002_contrat_prochainpay'),
    ]

    operations = [
        migrations.AddField(
            model_name='etablissement',
            name='margepay',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='facture',
            name='finaltotal',
            field=models.FloatField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='facture',
            name='retardfacture',
            field=models.FloatField(default=1),
            preserve_default=False,
        ),
    ]
