# Generated by Django 4.0.6 on 2022-08-03 21:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gimmo', '0003_etablissement_margepay_facture_finaltotal_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contrat',
            name='datefin',
            field=models.DateField(blank=True, default=None),
            preserve_default=False,
        ),
    ]
