# Generated by Django 4.0.6 on 2022-08-04 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gimmo', '0005_alter_contrat_datefin'),
    ]

    operations = [
        migrations.AddField(
            model_name='facture',
            name='debutpay',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='facture',
            name='dureepay',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='facture',
            name='finpay',
            field=models.DateField(blank=True, null=True),
        ),
    ]
